POST http://localhost:3000/family/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImlhdCI6MTc2MDQ2NjA1OX0.HJ7hyWu8Ni4Tdx_vPyaIjALd94nVXUo2D_LBCZ7usIg

{
    "familyName": "peppa familly",
    "inviteCode": "12345"
}

