DELETE http://localhost:3000/tasks/68f64b39c0b6ecccda0edf1f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImlhdCI6MTc2MDczMjU1NSwiZXhwIjoxNzYzMzI0NTU1fQ.P_-xbMEUjbhysBizvUMCDQuKOBzkhBzUUb7YWQwAZSc
