GET http://localhost:3000/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImZhbWlseUlkIjoiNjhlZTk0ZDQwYzEwZGUzNmJmZmE5NGRhIiwiaWF0IjoxNzYwNTQ1MzE4fQ.BgpD4Y_HrLnNQ8sisRXwd7jOoMCzYAiPPf1Rb8Zn1vE

{
    "familyId": "68ee94d40c10de36bffa94da"
}
