GET http://localhost:3000/family/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImlhdCI6MTc2MDczMjU1NSwiZXhwIjoxNzYzMzI0NTU1fQ.P_-xbMEUjbhysBizvUMCDQuKOBzkhBzUUb7YWQwAZSc

