GET http://localhost:3000/tasks/68f004040c080c6588dcc98d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImZhbWlseUlkIjoiNjhlZTk0ZDQwYzEwZGUzNmJmZmE5NGRhIiwiaWF0IjoxNzYwNjM3MTgzfQ.dtwz10qNKabQ0a6xUSdLBuz1e2nFWtAuUnAthjphWuc

{
    "familyId": "68ee94d40c10de36bffa94da"
}
