POST http://localhost:3000/family/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjJhYTg2N2U2ZjRjYTgyYTMyYTFmMiIsImlhdCI6MTc2MDczMzgzMCwiZXhwIjoxNzYzMzI1ODMwfQ.lEjeXIAyn21t8PC1zgH0562GSfAcjrhSbk_bDyZTLsk

{
    "inviteCode": "F66E4A"
}