//supervisor
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testMama@abc.com",
    "password": "password"
}

### peppa
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testbabyy1@abc.com",
    "password": "password"
}


### george
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testbabyy2@abc.com",
    "password": "password"
}