PATCH http://localhost:3000/tasks/status/68f638fbc0b6ecccda0ede7e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWU5NDhiMGMxMGRlMzZiZmZhOTRkNyIsImlhdCI6MTc2MDczMjU1NSwiZXhwIjoxNzYzMzI0NTU1fQ.P_-xbMEUjbhysBizvUMCDQuKOBzkhBzUUb7YWQwAZSc

{
    "status": "For_Approval"
}


### Peppa update
PATCH http://localhost:3000/tasks/status/68eea273c53064c14783bc17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZWVhMTY2YzUzMDY0YzE0NzgzYmMwNSIsImZhbWlseUlkIjoiNjhlZTk0ZDQwYzEwZGUzNmJmZmE5NGRhIiwiaWF0IjoxNzYwNTQ2MDIwfQ.WC2Ed2XZRnRCKIve2Yc1Jd3fd63NTO7hG0OwbAeot1k

{
    "status": "For_Approval"
}
